"""empty message

Revision ID: 17c72775d804
Revises: 
Create Date: 2025-06-07 22:09:05.612808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17c72775d804'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('harvests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_harvests_end_date'), 'harvests', ['end_date'], unique=False)
    op.create_index(op.f('ix_harvests_name'), 'harvests', ['name'], unique=False)
    op.create_index(op.f('ix_harvests_start_date'), 'harvests', ['start_date'], unique=False)
    op.create_table('producers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cpf_cnpj', sa.String(), nullable=False),
    sa.Column('document_type', sa.Enum('CPF', 'CNPJ', name='documenttypeenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_producers_cpf_cnpj'), 'producers', ['cpf_cnpj'], unique=True)
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('producer_id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.Enum('RONDONIA', 'ACRE', 'AMAZONAS', 'RORAIMA', 'PARA', 'AMAPA', 'TOCANTINS', 'MARANHAO', 'PIAUI', 'CEARA', 'RIO_GRANDE_DO_NORTE', 'PARAIBA', 'PERNAMBUCO', 'ALAGOAS', 'SERGIPE', 'BAHIA', 'MINAS_GERAIS', 'ESPIRITO_SANTO', 'RIO_DE_JANEIRO', 'SAO_PAULO', 'PARANA', 'SANTA_CATARINA', 'RIO_GRANDE_DO_SUL', 'MATO_GRO_DO_SUL', 'MATO_GROSSO', 'GOIAS', 'DISTRITO_FEDERAL', name='ufenum'), nullable=False),
    sa.Column('total_area', sa.Integer(), nullable=False),
    sa.Column('agricultural_area', sa.Integer(), nullable=False),
    sa.Column('area_vegetation', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['producer_id'], ['producers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plantings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('property_name', sa.String(), nullable=False),
    sa.Column('harvest_id', sa.Integer(), nullable=False),
    sa.Column('planted_area', sa.Integer(), nullable=False),
    sa.Column('crop_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['harvest_id'], ['harvests.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plantings_crop_name'), 'plantings', ['crop_name'], unique=False)
    op.create_index(op.f('ix_plantings_property_id'), 'plantings', ['property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plantings_property_id'), table_name='plantings')
    op.drop_index(op.f('ix_plantings_crop_name'), table_name='plantings')
    op.drop_table('plantings')
    op.drop_table('properties')
    op.drop_index(op.f('ix_producers_cpf_cnpj'), table_name='producers')
    op.drop_table('producers')
    op.drop_index(op.f('ix_harvests_start_date'), table_name='harvests')
    op.drop_index(op.f('ix_harvests_name'), table_name='harvests')
    op.drop_index(op.f('ix_harvests_end_date'), table_name='harvests')
    op.drop_table('harvests')
    # ### end Alembic commands ###
